# Generated by Django 3.2.5 on 2021-07-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='price',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
    ]
