# Generated by Django 3.2.5 on 2021-07-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0002_auto_20210726_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='number',
        ),
    ]
