# Generated by Django 3.2.5 on 2021-07-28 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0004_rename_number_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.CreateModel(
            name='Onenews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.ManyToManyField(to='News_Portal.News')),
            ],
        ),
    ]
