# Generated by Django 3.2.5 on 2021-07-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0003_auto_20210726_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='number',
            new_name='name',
        ),
    ]
