# Generated by Django 3.2.5 on 2021-08-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0005_auto_20210728_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onenews',
        ),
    ]
