# Generated by Django 3.2.5 on 2021-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0006_delete_onenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
